(function(root){
'use strict';
const step=(label,text,part,effect)=>({label,text,part,effect});
const templates=[
{id:'filter',name:'Fresh filter',complaint:'The air from my vents feels weak.',clue:'The filter is covered with dust. It catches dust before air reaches the blower.',part:'Filter',steps:[step('Open filter door','The filter door opens. The dusty filter is visible.','Filter','open'),step('Slide out dusty filter','The old filter slides into the recycling tray.','Filter','removed'),step('Choose matching fresh filter','A fresh pretend filter is ready on your work mat.','Filter','ready'),step('Turn airflow arrow toward blower','The arrow now points toward the blower, which moves the air.','Filter','aligned'),step('Slide fresh filter into slot','The clean filter fills the slot.','Filter','fitted'),step('Close filter door','The door is shut and the clean filter stays in place.','Filter','closed')]},
{id:'thermostat',name:'Comfort setting',complaint:'My room is warm, but cooling never starts.',clue:'The thermostat is set to OFF. It tells the system when to heat or cool.',part:'Thermostat',steps:[step('Open thermostat cover','The pretend thermostat controls are visible.','Thermostat','open'),step('Choose cooling mode','The display changes from OFF to COOL.','Thermostat','mode'),step('Choose comfortable target','The target changes to 72° for this pretend home.','Thermostat','target'),step('Choose automatic fan','The display now shows FAN AUTO.','Thermostat','auto'),step('Confirm display','COOL • 72° • AUTO appears on the display.','Thermostat','fitted'),step('Close thermostat cover','The thermostat cover clicks into place.','Thermostat','closed')]},
{id:'outdoor',name:'Clear outdoor space',complaint:'Cooling is weak and leaves surround my outdoor unit.',clue:'Leaves cover the outdoor air space. The outdoor fan moves air over the outdoor coil.',part:'Outdoor fan',steps:[step('Move loose leaves to bag','One pile of pretend leaves moves into the bag.','Outdoor fan','leaves'),step('Move toy away from unit','The toy moves to a safe shelf in the pretend scene.','Outdoor fan','toy'),step('Clear remaining loose leaves','The last loose leaves move to the bag.','Outdoor fan','removed'),step('Brush pretend outer screen','The screen is now visibly clear.','Outdoor fan','ready'),step('Check clear air space','Clear space surrounds the unit.','Outdoor fan','fitted'),step('Put cleanup bag away','The bag moves onto the work mat.','Outdoor fan','closed')]},
{id:'drain',name:'Free flowing drain',complaint:'There is water in the drain pan.',clue:'The pretend drain line is blocked. The pan catches water from the indoor coil; the line carries it away.',part:'Drain line',steps:[step('Place pretend catch tray','A catch tray sits beneath the game drain.','Drain line','tray'),step('Open game drain connector','The model connector separates. This is a toy repair.','Drain line','open'),step('Remove pretend clog token','The brown clog token moves into the tray.','Drain line','removed'),step('Slide clear line into place','The clear drain line connects to the pan.','Drain line','fitted'),step('Close game connector','The connector closes around the line.','Drain line','closed'),step('Pour pretend test water','Blue water flows through the line and the pan empties.','Drain line','flow')]},
{id:'fan',name:'Swap toy fan module',complaint:'My outdoor fan does not turn.',clue:'The toy fan module is stuck. The compressor below helps move cooling through the system.',part:'Outdoor fan',steps:[step('Open toy fan lid','The lid lifts from the model unit.','Outdoor fan','open'),step('Unclip toy fan module','A large pretend clip opens. No wiring is used in this game.','Outdoor fan','unclip'),step('Lift out stuck module','The stuck fan moves onto the mat.','Outdoor fan','removed'),step('Choose matching toy module','A fresh toy fan module waits beside the unit.','Outdoor fan','ready'),step('Fit and clip toy module','The new fan sits inside the model and the clip closes.','Outdoor fan','fitted'),step('Close toy fan lid','The fan lid sits back on the unit.','Outdoor fan','closed')]}
];
const customers=['Sam','Jordan','Alex','Morgan','Casey'];const places=['Garden cottage','Corner café','Blue townhouse','Community studio'];
function createJob(previous=null,first=false,rng=Math.random){const pool=templates.filter(t=>t.id!==previous);const fault=first?templates[0]:pool[Math.floor(rng()*pool.length)];return {fault:fault.id,customer:customers[Math.floor(rng()*customers.length)],place:places[Math.floor(rng()*places.length)],color:['#e6bd91','#b5c4e9','#b7d6ad'][Math.floor(rng()*3)]};}
function steps(job){const t=templates.find(t=>t.id===job.fault);return [step('Hear customer complaint',t.complaint,'Customer','heard'),step('Inspect '+t.part,t.clue,t.part,'inspected'),step('Set model power to OFF','The game power indicator turns OFF. Only pretend parts are used.','Power','off'),step('Place work mat','Your work mat and toy parts are ready.','Workspace','mat'),...t.steps,step('Put tools on mat','The tools rest on the mat and the workspace is tidy.','Workspace','tidy'),step('Set model power to ON','The game power indicator turns ON. Ready for a test.','Power','on'),step('Test repaired system','The fan turns, cool air reaches the room, and water drains away.','System','tested'),step('Show customer the result',job.customer+' says: Thank you! My room feels comfortable again.','Customer','thanks')];}
function valid(s){return s&&s.version===1&&[3,6,10].includes(s.target)&&Array.isArray(s.completed)&&s.completed.length<10000&&s.completed.every(j=>templates.some(t=>t.id===j.fault)&&customers.includes(j.customer)&&places.includes(j.place))&&s.job&&templates.some(t=>t.id===s.job.fault)&&customers.includes(s.job.customer)&&places.includes(s.job.place)&&['#e6bd91','#b5c4e9','#b7d6ad'].includes(s.job.color)&&Number.isInteger(s.step)&&s.step>=0&&s.step<=14;}
root.HVACModel={templates,createJob,steps,valid};
})(typeof window==='undefined'?globalThis:window);
