plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bestpolity.switchmatesolitaire'
    compileSdkVersion 36

    defaultConfig {
        applicationId 'com.bestpolity.switchmatesolitaire'
        minSdkVersion 23
        targetSdkVersion 36
        versionCode 4
        versionName '1.0.2'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
